development:
  adapter: sqlite3
  database: inkly_dev
  username: root
  password: 
  pool: 5
  timeout: 5000


test:
  adapter: sqlite3
  database: inkly_test
  username: root
  password: 
  pool: 5
  timeout: 5000